language: python
sudo: true

install:
  - sudo pip --quiet install -r requirements.txt

script:
  - git config --global credential.helper store
  - git clone https://${DEPLOY_USER}:${DEPLOY_PASSWD}@github.com/EtchDroid/LibreSSL.git
  - export LSSLM_GIT_REPO="$(pwd)/LibreSSL"
  - python3 libressl_automirror.py
